# Generated by Django 2.2.13 on 2021-07-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210710_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='episode_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Episode I'), (2, 'Episode II'), (3, 'Episode III'), (4, 'Episode IV'), (5, 'Episode V'), (6, 'Episode VI'), (7, 'Episode VII'), (8, 'Episode VIII'), (9, 'Episode IX')]),
        ),
    ]
